services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./volumes/postgres_storage:/var/lib/postgresql

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    env_file:
      - ./.env
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./volumes/qdrant_storage:/qdrant/storage:z

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ./.env
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis_storage:/data/
